from detectron2.config import CfgNode as CN


def add_dinov2_vit_adapter_regofficial_config(cfg):
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL = CN()
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.PRETRAINED = ""
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.IMG_SIZE = 592
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.PATCH_SIZE = 16
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.EMBED_DIM = 1024
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.DEPTH = 24
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.NUM_HEADS = 16
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.MLP_RATIO = 4.0
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.DROP_PATH_RATE = 0.4
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.INIT_VALUES = 1.0
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.NUM_REGISTER_TOKENS = 4
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.INTERPOLATE_ANTIALIAS = True
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.INTERPOLATE_OFFSET = 0.0
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.CONV_INPLANE = 64
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.N_POINTS = 4
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.DEFORM_NUM_HEADS = 16
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.INTERACTION_INDEXES = [[0, 5], [6, 11], [12, 17], [18, 23]]
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.WITH_CFFN = True
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.CFFN_RATIO = 0.25
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.DEFORM_RATIO = 1.0
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.ADD_VIT_FEATURE = True
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.USE_EXTRA_EXTRACTOR = True
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.FREEZE_VIT = False
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.STRICT_PRETRAIN_LOAD = True
    cfg.MODEL.DINO_ADAPTER_REGOFFICIAL.OUT_FEATURES = ["res2", "res3", "res4", "res5"]
