from __future__ import annotations
import json
from pathlib import Path
from typing import Any, Dict
from videocutler.ext_stageb_ovvis.pipeline.plans import TrainPlan
from videocutler.ext_stageb_ovvis.data.g7_phase1_materialization import Phase1MaterializationConfig, materialize_phase1_training_samples
from videocutler.ext_stageb_ovvis.algorithms.prealign import PrealignConfig, train_prealign
from videocutler.ext_stageb_ovvis.algorithms.soft_em import SoftEMConfig, run_soft_em
from videocutler.ext_stageb_ovvis.algorithms.reservoir_v1 import ReservoirPrealignConfig, ReservoirSoftEMConfig, train_reservoir_prealign, run_reservoir_soft_em

def _write_json(path: Path, payload: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True); path.write_text(json.dumps(payload, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
def _materialize(plan: TrainPlan):
    return materialize_phase1_training_samples(plan.output_root, Phase1MaterializationConfig(dataset_name=plan.dataset_name, trajectory_source_branch=plan.trajectory_source_branch, smoke=plan.smoke, smoke_max_trajectories=plan.smoke_max_trajectories, subset_fraction=plan.subset_fraction, subset_seed=plan.seed))
def run_train_pipeline(plan: TrainPlan) -> Dict[str, Any]:
    materialized=_materialize(plan); summary={'exp_name':plan.exp_name,'pipeline':plan.pipeline,'stage_scope':plan.stage_scope,'dataset_name':plan.dataset_name,'trajectory_source_branch':plan.trajectory_source_branch,'smoke':plan.smoke,'resolution':materialized['resolution'],'materialization_stats':materialized['stats'],'stages':{}}
    if plan.pipeline=='legacy':
        pre=train_prealign(output_root=plan.output_root, materialized_samples=materialized['samples'], config=PrealignConfig(dataset_name=plan.dataset_name, trajectory_source_branch=plan.trajectory_source_branch, device=plan.device, seed=plan.seed, smoke=plan.smoke, epochs=(1 if plan.smoke else 5) if plan.prealign_epochs is None else plan.prealign_epochs, learning_rate=(1e-4 if plan.prealign_learning_rate is None else plan.prealign_learning_rate), weight_decay=plan.weight_decay, t_dis_init=plan.t_dis_init, lambda_frame=(0.25 if plan.lambda_frame is None else plan.lambda_frame), runtime_asset_source=str(materialized['resolution'].get('runtime_asset_source','local_canonical_assets')), runtime_asset_source_local_incomplete=bool(materialized['resolution'].get('local_incomplete',False)), runtime_asset_output_root=str(materialized['resolution'].get('runtime_output_root', str(plan.output_root))), batch_budget=plan.batch_budget, show_progress=plan.show_progress, log_every=plan.log_every, write_runtime_metrics_jsonl=plan.write_runtime_metrics_jsonl, print_epoch_summary=plan.print_epoch_summary)); summary['stages']['prealign']=pre
        if plan.stage_scope!='prealign_only':
            mode='base_only' if plan.stage_scope=='prealign_base' else 'base_then_aug'
            soft=run_soft_em(output_root=plan.output_root, materialized_samples=materialized['samples'], config=SoftEMConfig(dataset_name=plan.dataset_name, trajectory_source_branch=plan.trajectory_source_branch, mode=mode, device=plan.device, seed=plan.seed, smoke=plan.smoke, lambda_frame=(0.25 if plan.lambda_frame is None else plan.lambda_frame), lambda_cov=plan.lambda_cov, t_dis_init=plan.t_dis_init, weight_decay=plan.weight_decay, base_epochs=(1 if plan.smoke else 5) if plan.base_epochs is None else plan.base_epochs, aug_epochs=(1 if plan.smoke else 5) if plan.aug_epochs is None else plan.aug_epochs, base_learning_rate=(5e-5 if plan.base_learning_rate is None else plan.base_learning_rate), aug_learning_rate=(5e-5 if plan.aug_learning_rate is None else plan.aug_learning_rate), runtime_asset_source=str(materialized['resolution'].get('runtime_asset_source','local_canonical_assets')), runtime_asset_source_local_incomplete=bool(materialized['resolution'].get('local_incomplete',False)), runtime_asset_output_root=str(materialized['resolution'].get('runtime_output_root', str(plan.output_root))), batch_budget=plan.batch_budget, show_progress=plan.show_progress, log_every=plan.log_every, write_runtime_metrics_jsonl=plan.write_runtime_metrics_jsonl, print_epoch_summary=plan.print_epoch_summary)); summary['stages']['softem']=soft
    else:
        pre=train_reservoir_prealign(output_root=plan.output_root, materialized_samples=materialized['samples'], config=ReservoirPrealignConfig(dataset_name=plan.dataset_name, trajectory_source_branch=plan.trajectory_source_branch, device=plan.device, seed=plan.seed, smoke=plan.smoke, epochs=(1 if plan.smoke else 5) if plan.prealign_epochs is None else plan.prealign_epochs, learning_rate=(1e-4 if plan.prealign_learning_rate is None else plan.prealign_learning_rate), weight_decay=plan.weight_decay, t_dis_init=plan.t_dis_init, lambda_frame=(0.25 if plan.lambda_frame is None else plan.lambda_frame), runtime_asset_source=str(materialized['resolution'].get('runtime_asset_source','local_canonical_assets')), runtime_asset_source_local_incomplete=bool(materialized['resolution'].get('local_incomplete',False)), runtime_asset_output_root=str(materialized['resolution'].get('runtime_output_root', str(plan.output_root))), batch_budget=plan.batch_budget, show_progress=plan.show_progress, log_every=plan.log_every, write_runtime_metrics_jsonl=plan.write_runtime_metrics_jsonl, print_epoch_summary=plan.print_epoch_summary)); summary['stages']['prealign']=pre
        if plan.stage_scope!='prealign_only':
            mode='base_only' if plan.stage_scope=='prealign_base' else 'base_then_aug'
            soft=run_reservoir_soft_em(output_root=plan.output_root, materialized_samples=materialized['samples'], config=ReservoirSoftEMConfig(dataset_name=plan.dataset_name, trajectory_source_branch=plan.trajectory_source_branch, mode=mode, device=plan.device, seed=plan.seed, smoke=plan.smoke, lambda_frame=(0.25 if plan.lambda_frame is None else plan.lambda_frame), t_dis_init=plan.t_dis_init, weight_decay=plan.weight_decay, base_epochs=(1 if plan.smoke else 5) if plan.base_epochs is None else plan.base_epochs, aug_epochs=(1 if plan.smoke else 5) if plan.aug_epochs is None else plan.aug_epochs, base_learning_rate=(5e-5 if plan.base_learning_rate is None else plan.base_learning_rate), aug_learning_rate=(5e-5 if plan.aug_learning_rate is None else plan.aug_learning_rate), runtime_asset_source=str(materialized['resolution'].get('runtime_asset_source','local_canonical_assets')), runtime_asset_source_local_incomplete=bool(materialized['resolution'].get('local_incomplete',False)), runtime_asset_output_root=str(materialized['resolution'].get('runtime_output_root', str(plan.output_root))), batch_budget=plan.batch_budget, show_progress=plan.show_progress, log_every=plan.log_every, write_runtime_metrics_jsonl=plan.write_runtime_metrics_jsonl, print_epoch_summary=plan.print_epoch_summary)); summary['stages']['softem']=soft
    out_path=plan.output_root/'train'/'pipeline_train_summary.json'; _write_json(out_path, summary); return {'status':'PASS','summary_path':str(out_path),'summary':summary}
