#!/usr/bin/env python3
"""Run Stage D9 OFF/ON entrypoint smoke and assert key no-op signals.

This helper wraps the real Sacred/SeqFormer entrypoint with fixed minimal smoke
settings and avoids fragile shell quoting for nested overrides.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


def _resolve_existing_path(candidates: list[Path]) -> Path:
    for candidate in candidates:
        if candidate.exists():
            return candidate
    rendered = ", ".join(str(x) for x in candidates)
    raise FileNotFoundError(f"none of the candidate paths exist: {rendered}")


def _write_smoke_config(
    path: Path,
    *,
    weights_path: Path,
    train_json: Path,
    train_img_root: Path,
    val_json: Path,
    val_img_root: Path,
) -> None:
    text = f"""# Auto-generated by tools/run_stage_d9_smoke_helper.py
# Minimal config for D9 entrypoint smoke only.
d2_cfg_path: third_party/VNext/projects/SeqFormer/configs/vnext_dinov2_ytvis.yaml
d2_opts:
  - DATASETS.TRAIN
  - (\"ytvis_wsovvis_lvvis_pseudo_train\",)
  - MODEL.SeqFormer.NUM_CLASSES
  - 1
  - MODEL.SeqFormer.MULTI_CLS_ON
  - False
  - MODEL.WEIGHTS
  - \"{weights_path}\"
  - SOLVER.MAX_ITER
  - 1
  - SOLVER.IMS_PER_BATCH
  - 1
  - DATALOADER.NUM_WORKERS
  - 0

data:
  train_name: ytvis_wsovvis_lvvis_pseudo_train
  train_json: "{train_json}"
  train_img_root: "{train_img_root}"
  val_name: null
  val_json: "{val_json}"
  val_img_root: "{val_img_root}"
  num_classes: 1

output_root: runs/wsovvis_seqformer
seed: 42
resume: false
eval_only: false
num_gpus: 1
num_machines: 1
machine_rank: 0
dist_url: tcp://127.0.0.1:29500
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _run(cmd: list[str], cwd: Path) -> None:
    print("RUN:", " ".join(cmd), flush=True)
    proc = subprocess.run(cmd, cwd=str(cwd), check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"command failed rc={proc.returncode}: {' '.join(cmd)}")


def _load_metrics_rows(metrics_path: Path) -> list[dict[str, Any]]:
    if not metrics_path.exists():
        raise FileNotFoundError(f"missing metrics file: {metrics_path}")
    rows: list[dict[str, Any]] = []
    for line in metrics_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        row = json.loads(line)
        if isinstance(row, dict):
            rows.append(row)
    if not rows:
        raise RuntimeError(f"no JSON rows found in metrics file: {metrics_path}")
    return rows


def _extract_last_numeric(rows: list[dict[str, Any]], key: str) -> float:
    for row in reversed(rows):
        value = row.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            return float(value)
    raise RuntimeError(f"no numeric '{key}' found in metrics rows")


def _find_metrics_file(run_dir: Path) -> Path:
    candidates = sorted(run_dir.glob("*/d2/metrics.json"))
    if not candidates:
        raise FileNotFoundError(f"no metrics.json under {run_dir}")
    return candidates[-1]


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Run D9 OFF/ON short entrypoint smoke and validate loss_stage_d_attr "
            "absence/presence + weight=0 parity."
        )
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path("."),
        help="Repository root containing train_seqformer_pseudo.py (default: current dir)",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("/tmp/wsovvis_stage_d9_smoke"),
        help="Root directory for OFF/ON Sacred file storage",
    )
    parser.add_argument(
        "--config-path",
        type=Path,
        default=Path("/tmp/wsovvis_d9_smoke_cfg.yaml"),
        help="Path where generated smoke YAML is written",
    )
    parser.add_argument(
        "--stagec-artifact-root",
        type=Path,
        default=Path("tests/fixtures/stage_d_smoke_artifacts"),
        help="Stage-C artifact root used by ON path",
    )
    parser.add_argument(
        "--weights-path",
        type=Path,
        default=None,
        help="Optional explicit model weights path",
    )
    parser.add_argument(
        "--train-json",
        type=Path,
        default=None,
        help="Optional explicit train pseudo-tube JSON path",
    )
    parser.add_argument(
        "--train-img-root",
        type=Path,
        default=None,
        help="Optional explicit train image root",
    )
    parser.add_argument(
        "--val-json",
        type=Path,
        default=None,
        help="Optional explicit val annotation JSON path",
    )
    parser.add_argument(
        "--val-img-root",
        type=Path,
        default=None,
        help="Optional explicit val image root",
    )
    parser.add_argument(
        "--python-bin",
        default=sys.executable,
        help="Python executable for train_seqformer_pseudo.py",
    )
    parser.add_argument(
        "--total-loss-key",
        default="total_loss",
        help="Metrics key used for parity check",
    )
    parser.add_argument(
        "--parity-tol",
        type=float,
        default=1e-9,
        help="Absolute tolerance for OFF/ON total loss parity",
    )
    parser.add_argument(
        "--keep-output",
        action="store_true",
        help="Do not delete existing output-root before running",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    output_root = args.output_root.resolve()
    config_path = args.config_path.resolve()
    off_dir = output_root / "off"
    on_dir = output_root / "on"

    if not args.keep_output and output_root.exists():
        shutil.rmtree(output_root)

    live_root = repo_root.parent / "wsovvis_live"
    weights_path = (
        args.weights_path
        if args.weights_path is not None
        else _resolve_existing_path(
            [
                repo_root / "runs/wsovvis_seqformer/15/d2/model_0005999.pth",
                live_root / "runs/wsovvis_seqformer/15/d2/model_0005999.pth",
            ]
        )
    )
    train_json = (
        args.train_json
        if args.train_json is not None
        else _resolve_existing_path(
            [
                repo_root / "outputs/videocutler_lvvis_png/train/pseudo_tube_ytvis.json",
                live_root / "outputs/videocutler_lvvis_png/train/pseudo_tube_ytvis.json",
            ]
        )
    )
    train_img_root = (
        args.train_img_root
        if args.train_img_root is not None
        else _resolve_existing_path(
            [
                repo_root / "data/LV-VIS/train/JPEGImages",
                live_root / "data/LV-VIS/train/JPEGImages",
            ]
        )
    )
    val_json = (
        args.val_json
        if args.val_json is not None
        else _resolve_existing_path(
            [
                repo_root / "data/LV-VIS/annotations/lvvis_val_agnostic.json",
                live_root / "data/LV-VIS/annotations/lvvis_val_agnostic.json",
            ]
        )
    )
    val_img_root = (
        args.val_img_root
        if args.val_img_root is not None
        else _resolve_existing_path(
            [
                repo_root / "data/LV-VIS/val/JPEGImages",
                live_root / "data/LV-VIS/val/JPEGImages",
            ]
        )
    )

    _write_smoke_config(
        config_path,
        weights_path=weights_path.resolve(),
        train_json=train_json.resolve(),
        train_img_root=train_img_root.resolve(),
        val_json=val_json.resolve(),
        val_img_root=val_img_root.resolve(),
    )

    train_script = repo_root / "train_seqformer_pseudo.py"
    if not train_script.exists():
        raise FileNotFoundError(f"missing train script: {train_script}")

    off_cmd = [
        args.python_bin,
        str(train_script),
        "-F",
        str(off_dir),
        "with",
        str(config_path),
    ]

    on_cmd = [
        args.python_bin,
        str(train_script),
        "-F",
        str(on_dir),
        "with",
        str(config_path),
        "stage_d_attribution.enabled=True",
        f"stage_d_attribution.stagec_artifact_root={args.stagec_artifact_root}",
        "stage_d_attribution.objective_coupling.enabled=True",
        "stage_d_attribution.objective_coupling.weight=0.0",
        "stage_d_attribution.additive_loss_key.enabled=True",
        "stage_d_attribution.additive_loss_key.weight=0.0",
    ]

    _run(off_cmd, cwd=repo_root)
    _run(on_cmd, cwd=repo_root)

    off_metrics = _find_metrics_file(off_dir)
    on_metrics = _find_metrics_file(on_dir)
    off_rows = _load_metrics_rows(off_metrics)
    on_rows = _load_metrics_rows(on_metrics)

    off_has_attr = any("loss_stage_d_attr" in row for row in off_rows)
    on_attr_values = [float(row["loss_stage_d_attr"]) for row in on_rows if "loss_stage_d_attr" in row]
    on_has_attr = len(on_attr_values) > 0
    on_last_attr = on_attr_values[-1] if on_attr_values else math.nan

    off_total = _extract_last_numeric(off_rows, args.total_loss_key)
    on_total = _extract_last_numeric(on_rows, args.total_loss_key)
    total_diff = abs(off_total - on_total)
    parity_ok = total_diff <= args.parity_tol

    on_zero_ok = on_has_attr and abs(on_last_attr) <= args.parity_tol
    checks_ok = (not off_has_attr) and on_zero_ok and parity_ok

    print(f"D10_OFF_METRICS={off_metrics}")
    print(f"D10_ON_METRICS={on_metrics}")
    print(f"D10_OFF_HAS_LOSS_STAGE_D_ATTR={off_has_attr}")
    print(f"D10_ON_HAS_LOSS_STAGE_D_ATTR={on_has_attr}")
    print(f"D10_ON_LOSS_STAGE_D_ATTR={on_last_attr}")
    print(f"D10_OFF_TOTAL_LOSS={off_total:.15f}")
    print(f"D10_ON_TOTAL_LOSS={on_total:.15f}")
    print(f"D10_TOTAL_LOSS_DIFF={total_diff:.15f}")
    print(f"D10_PARITY_TOL={args.parity_tol}")
    print(f"D10_CHECKS_PASS={checks_ok}")

    if checks_ok:
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
