#!/usr/bin/env python3
"""Run Stage D9 OFF/ON entrypoint smoke and assert key no-op signals.

This helper wraps the real Sacred/SeqFormer entrypoint with fixed minimal smoke
settings and avoids fragile shell quoting for nested overrides.
"""

from __future__ import annotations

import argparse
import json
import math
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


def _require_mapping(value: Any, *, field_name: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise RuntimeError(f"{field_name} must be an object")
    return value


def _require_bool(value: Any, *, field_name: str) -> bool:
    if not isinstance(value, bool):
        raise RuntimeError(f"{field_name} must be a boolean")
    return value


def _require_str(value: Any, *, field_name: str) -> str:
    if not isinstance(value, str) or not value:
        raise RuntimeError(f"{field_name} must be a non-empty string")
    return value


def _require_number(value: Any, *, field_name: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise RuntimeError(f"{field_name} must be numeric")
    return float(value)


def _resolve_existing_path(candidates: list[Path]) -> Path:
    for candidate in candidates:
        if candidate.exists():
            return candidate
    rendered = ", ".join(str(x) for x in candidates)
    raise FileNotFoundError(f"none of the candidate paths exist: {rendered}")


def _write_smoke_config(
    path: Path,
    *,
    weights_path: Path,
    train_json: Path,
    train_img_root: Path,
    val_json: Path,
    val_img_root: Path,
) -> None:
    text = f"""# Auto-generated by tools/run_stage_d9_smoke_helper.py
# Minimal config for D9 entrypoint smoke only.
d2_cfg_path: third_party/VNext/projects/SeqFormer/configs/vnext_dinov2_ytvis.yaml
d2_opts:
  - DATASETS.TRAIN
  - (\"ytvis_wsovvis_lvvis_pseudo_train\",)
  - DATASETS.TEST
  - (\"ytvis_wsovvis_lvvis_val_agnostic\",)
  - MODEL.SeqFormer.NUM_CLASSES
  - 1
  - MODEL.SeqFormer.MULTI_CLS_ON
  - False
  - MODEL.WEIGHTS
  - \"{weights_path}\"
  - TEST.EVAL_PERIOD
  - 0
  - SOLVER.MAX_ITER
  - 1
  - SOLVER.IMS_PER_BATCH
  - 1
  - DATALOADER.NUM_WORKERS
  - 0

data:
  train_name: ytvis_wsovvis_lvvis_pseudo_train
  train_json: "{train_json}"
  train_img_root: "{train_img_root}"
  val_name: ytvis_wsovvis_lvvis_val_agnostic
  val_json: "{val_json}"
  val_img_root: "{val_img_root}"
  num_classes: 1

output_root: runs/wsovvis_seqformer
seed: 42
resume: false
eval_only: false
num_gpus: 1
num_machines: 1
machine_rank: 0
dist_url: tcp://127.0.0.1:29500
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _build_tiny_eval_json(*, source_train_json: Path, output_json: Path) -> Path:
    data = json.loads(source_train_json.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise RuntimeError(f"unexpected train json type: {type(data)!r}")
    videos = data.get("videos")
    if not isinstance(videos, list) or not videos:
        raise RuntimeError("train json has no videos to build tiny eval dataset")
    first_video = videos[0]
    if not isinstance(first_video, dict):
        raise RuntimeError("train json first video is not an object")

    tiny_video = {
        "id": first_video.get("id", 1),
        "width": first_video["width"],
        "height": first_video["height"],
        "length": first_video["length"],
        "file_names": first_video["file_names"],
    }
    tiny = {
        "videos": [tiny_video],
        "annotations": [],
        "categories": [{"id": 1, "name": "object"}],
    }
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(tiny), encoding="utf-8")
    return output_json


def _run(cmd: list[str], cwd: Path) -> None:
    print("RUN:", " ".join(cmd), flush=True)
    proc = subprocess.run(cmd, cwd=str(cwd), check=False)
    if proc.returncode != 0:
        raise RuntimeError(f"command failed rc={proc.returncode}: {' '.join(cmd)}")


def _load_metrics_rows(metrics_path: Path) -> list[dict[str, Any]]:
    if not metrics_path.exists():
        raise FileNotFoundError(f"missing metrics file: {metrics_path}")
    rows: list[dict[str, Any]] = []
    for line in metrics_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        row = json.loads(line)
        if isinstance(row, dict):
            rows.append(row)
    if not rows:
        raise RuntimeError(f"no JSON rows found in metrics file: {metrics_path}")
    return rows


def _extract_last_numeric(rows: list[dict[str, Any]], key: str) -> float:
    for row in reversed(rows):
        value = row.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            return float(value)
    raise RuntimeError(f"no numeric '{key}' found in metrics rows")


def _find_metrics_file(run_dir: Path) -> Path:
    candidates = sorted(run_dir.glob("*/d2/metrics.json"))
    if not candidates:
        raise FileNotFoundError(f"no metrics.json under {run_dir}")
    return candidates[-1]


def _load_runtime_cfg(run_dir: Path) -> dict[str, Any]:
    cfg_path = run_dir / "cfg_runtime.json"
    if not cfg_path.exists():
        raise FileNotFoundError(f"missing runtime cfg file: {cfg_path}")
    payload = json.loads(cfg_path.read_text(encoding="utf-8"))
    cfg = _require_mapping(payload, field_name="cfg_runtime.json")
    return cfg


def _evaluate_pilot_diagnostics_checks(
    *,
    on_mode: str,
    on_runtime_cfg: dict[str, Any],
    expected_weight: float,
    pilot_scale: float | None,
    value_tol: float = 1e-12,
) -> dict[str, Any]:
    if on_mode != "pilot":
        return {
            "enabled": False,
            "checks_ok": True,
            "reason": "not_pilot_mode",
        }

    d6 = _require_mapping(
        on_runtime_cfg.get("stage_d_attribution_d6_loss_key"),
        field_name="stage_d_attribution_d6_loss_key",
    )
    diagnostics = _require_mapping(d6.get("diagnostics"), field_name="stage_d_attribution_d6_loss_key.diagnostics")
    planned_loss = _require_mapping(d6.get("planned_loss"), field_name="stage_d_attribution_d6_loss_key.planned_loss")

    nonzero_mode = _require_str(d6.get("nonzero_semantics_mode"), field_name="stage_d_attribution_d6_loss_key.nonzero_semantics_mode")
    if nonzero_mode != "gradient_coupled_pilot_v1":
        raise RuntimeError(
            "stage_d_attribution_d6_loss_key.nonzero_semantics_mode must be gradient_coupled_pilot_v1 for pilot mode"
        )
    nonzero_enabled = _require_bool(
        d6.get("nonzero_semantics_enabled_by_config"),
        field_name="stage_d_attribution_d6_loss_key.nonzero_semantics_enabled_by_config",
    )
    if not nonzero_enabled:
        raise RuntimeError("pilot mode requires nonzero semantics to be enabled by config")

    loss_weight = _require_number(planned_loss.get("loss_weight"), field_name="stage_d_attribution_d6_loss_key.planned_loss.loss_weight")
    if abs(loss_weight - expected_weight) > value_tol:
        raise RuntimeError(
            "stage_d_attribution_d6_loss_key.planned_loss.loss_weight mismatch: "
            f"expected {expected_weight}, got {loss_weight}"
        )

    gradient_scale = _require_number(
        planned_loss.get("gradient_coupled_scale"),
        field_name="stage_d_attribution_d6_loss_key.planned_loss.gradient_coupled_scale",
    )
    if pilot_scale is not None and abs(gradient_scale - float(pilot_scale)) > value_tol:
        raise RuntimeError(
            "stage_d_attribution_d6_loss_key.planned_loss.gradient_coupled_scale mismatch: "
            f"expected {pilot_scale}, got {gradient_scale}"
        )

    pilot_applied = _require_bool(
        diagnostics.get("gradient_coupled_pilot_applied"),
        field_name="stage_d_attribution_d6_loss_key.diagnostics.gradient_coupled_pilot_applied",
    )
    pilot_state = _require_str(
        diagnostics.get("gradient_coupled_pilot_state"),
        field_name="stage_d_attribution_d6_loss_key.diagnostics.gradient_coupled_pilot_state",
    )
    pilot_skip_reason = _require_str(
        diagnostics.get("gradient_coupled_pilot_skip_reason"),
        field_name="stage_d_attribution_d6_loss_key.diagnostics.gradient_coupled_pilot_skip_reason",
    )
    nonzero_state = _require_str(
        diagnostics.get("nonzero_semantics_state"),
        field_name="stage_d_attribution_d6_loss_key.diagnostics.nonzero_semantics_state",
    )
    nonzero_skip_reason = _require_str(
        diagnostics.get("nonzero_skip_reason"),
        field_name="stage_d_attribution_d6_loss_key.diagnostics.nonzero_skip_reason",
    )

    if pilot_applied:
        if pilot_state != "applied" or pilot_skip_reason != "none":
            raise RuntimeError("pilot diagnostics inconsistent: applied=True requires pilot_state=applied and pilot_skip_reason=none")
        if nonzero_state != "nonzero_applied" or nonzero_skip_reason != "none":
            raise RuntimeError(
                "pilot diagnostics inconsistent: applied=True requires nonzero_semantics_state=nonzero_applied and nonzero_skip_reason=none"
            )
    else:
        if pilot_state != "skipped":
            raise RuntimeError("pilot diagnostics inconsistent: applied=False requires pilot_state=skipped")
        if pilot_skip_reason == "none":
            raise RuntimeError("pilot diagnostics inconsistent: applied=False requires a non-none pilot skip reason")
        if nonzero_state != "skipped":
            raise RuntimeError("pilot diagnostics inconsistent: applied=False requires nonzero_semantics_state=skipped")
        if nonzero_skip_reason == "none":
            raise RuntimeError("pilot diagnostics inconsistent: applied=False requires a non-none nonzero skip reason")

    return {
        "enabled": True,
        "checks_ok": True,
        "nonzero_mode": nonzero_mode,
        "nonzero_enabled": nonzero_enabled,
        "loss_weight": loss_weight,
        "gradient_coupled_scale": gradient_scale,
        "pilot_applied": pilot_applied,
        "pilot_state": pilot_state,
        "pilot_skip_reason": pilot_skip_reason,
        "nonzero_state": nonzero_state,
        "nonzero_skip_reason": nonzero_skip_reason,
    }


def _evaluate_metrics_checks(
    *,
    off_rows: list[dict[str, Any]],
    on_rows: list[dict[str, Any]],
    total_loss_key: str,
    parity_tol: float,
    expect_nonzero_on: bool = False,
    nonzero_eps: float = 1e-12,
) -> dict[str, Any]:
    off_has_attr = any("loss_stage_d_attr" in row for row in off_rows)
    on_attr_values = [float(row["loss_stage_d_attr"]) for row in on_rows if "loss_stage_d_attr" in row]
    on_has_attr = len(on_attr_values) > 0
    on_last_attr = on_attr_values[-1] if on_attr_values else math.nan

    off_total = _extract_last_numeric(off_rows, total_loss_key)
    on_total = _extract_last_numeric(on_rows, total_loss_key)
    total_diff = abs(off_total - on_total)
    parity_ok = total_diff <= parity_tol
    on_zero_ok = on_has_attr and abs(on_last_attr) <= parity_tol
    on_nonzero_ok = on_has_attr and abs(on_last_attr) > nonzero_eps
    on_total_increase = on_total - off_total
    total_increase_ok = on_total_increase > nonzero_eps
    checks_ok = (
        (not off_has_attr)
        and (on_nonzero_ok and total_increase_ok if expect_nonzero_on else (on_zero_ok and parity_ok))
    )

    return {
        "expect_nonzero_on": expect_nonzero_on,
        "off_has_attr": off_has_attr,
        "on_has_attr": on_has_attr,
        "on_last_attr": on_last_attr,
        "off_total": off_total,
        "on_total": on_total,
        "total_diff": total_diff,
        "on_total_increase": on_total_increase,
        "parity_ok": parity_ok,
        "on_zero_ok": on_zero_ok,
        "on_nonzero_ok": on_nonzero_ok,
        "total_increase_ok": total_increase_ok,
        "checks_ok": checks_ok,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Run D9 OFF/ON short entrypoint smoke and validate loss_stage_d_attr "
            "absence/presence with either weight=0 parity or nonzero-weight ON-path checks."
        )
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path("."),
        help="Repository root containing train_seqformer_pseudo.py (default: current dir)",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("/tmp/wsovvis_stage_d9_smoke"),
        help="Root directory for OFF/ON Sacred file storage",
    )
    parser.add_argument(
        "--config-path",
        type=Path,
        default=Path("/tmp/wsovvis_d9_smoke_cfg.yaml"),
        help="Path where generated smoke YAML is written",
    )
    parser.add_argument(
        "--stagec-artifact-root",
        type=Path,
        default=Path("tests/fixtures/stage_d_smoke_artifacts"),
        help="Stage-C artifact root used by ON path",
    )
    parser.add_argument(
        "--weights-path",
        type=Path,
        default=None,
        help="Optional explicit model weights path",
    )
    parser.add_argument(
        "--train-json",
        type=Path,
        default=None,
        help="Optional explicit train pseudo-tube JSON path",
    )
    parser.add_argument(
        "--train-img-root",
        type=Path,
        default=None,
        help="Optional explicit train image root",
    )
    parser.add_argument(
        "--val-json",
        type=Path,
        default=None,
        help="Optional explicit val annotation JSON path",
    )
    parser.add_argument(
        "--val-img-root",
        type=Path,
        default=None,
        help="Optional explicit val image root",
    )
    parser.add_argument(
        "--python-bin",
        default=sys.executable,
        help="Python executable for train_seqformer_pseudo.py",
    )
    parser.add_argument(
        "--total-loss-key",
        default="total_loss",
        help="Metrics key used for parity check",
    )
    parser.add_argument(
        "--parity-tol",
        type=float,
        default=1e-9,
        help="Absolute tolerance for OFF/ON total loss parity",
    )
    parser.add_argument(
        "--on-mode",
        choices=("zero", "nonzero", "pilot"),
        default="zero",
        help=(
            "ON-path semantic mode: zero (default sentinel), nonzero (constant mode), "
            "or pilot (gradient_coupled_pilot_v1)"
        ),
    )
    parser.add_argument(
        "--on-weight",
        type=float,
        default=None,
        help="Explicit ON-path additive weight (default: 0.0 for zero mode, 0.25 for nonzero/pilot modes)",
    )
    parser.add_argument(
        "--pilot-scale",
        type=float,
        default=None,
        help=(
            "Optional gradient-coupled pilot scale override for "
            "nonzero_semantics.mode=gradient_coupled_pilot_v1 (default: helper leaves unset)"
        ),
    )
    parser.add_argument(
        "--nonzero-eps",
        type=float,
        default=1e-12,
        help="Strict positivity threshold for ON nonzero checks",
    )
    parser.add_argument(
        "--keep-output",
        action="store_true",
        help="Do not delete existing output-root before running",
    )
    parser.add_argument(
        "--dry-run",
        "--print-commands-only",
        action="store_true",
        help="Print resolved OFF/ON train commands and exit without executing",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    output_root = args.output_root.resolve()
    config_path = args.config_path.resolve()
    off_dir = output_root / "off"
    on_dir = output_root / "on"

    if not args.keep_output and output_root.exists():
        shutil.rmtree(output_root)

    live_root = repo_root.parent / "wsovvis_live"
    if args.dry_run:
        weights_path = (
            args.weights_path
            if args.weights_path is not None
            else repo_root / "runs/wsovvis_seqformer/15/d2/model_0005999.pth"
        )
        train_json = (
            args.train_json
            if args.train_json is not None
            else repo_root / "outputs/videocutler_lvvis_png/train/pseudo_tube_ytvis.json"
        )
        train_img_root = (
            args.train_img_root
            if args.train_img_root is not None
            else repo_root / "data/LV-VIS/train/JPEGImages"
        )
        val_json = (
            args.val_json if args.val_json is not None else output_root / "tiny_eval_ytvis.json"
        )
        if args.val_img_root is not None:
            val_img_root = args.val_img_root
        elif args.val_json is None:
            val_img_root = train_img_root
        else:
            val_img_root = repo_root / "data/LV-VIS/val/JPEGImages"
    else:
        weights_path = (
            args.weights_path
            if args.weights_path is not None
            else _resolve_existing_path(
                [
                    repo_root / "runs/wsovvis_seqformer/15/d2/model_0005999.pth",
                    live_root / "runs/wsovvis_seqformer/15/d2/model_0005999.pth",
                ]
            )
        )
        train_json = (
            args.train_json
            if args.train_json is not None
            else _resolve_existing_path(
                [
                    repo_root / "outputs/videocutler_lvvis_png/train/pseudo_tube_ytvis.json",
                    live_root / "outputs/videocutler_lvvis_png/train/pseudo_tube_ytvis.json",
                ]
            )
        )
        train_img_root = (
            args.train_img_root
            if args.train_img_root is not None
            else _resolve_existing_path(
                [
                    repo_root / "data/LV-VIS/train/JPEGImages",
                    live_root / "data/LV-VIS/train/JPEGImages",
                ]
            )
        )
        if args.val_json is not None:
            val_json = args.val_json
        else:
            val_json = _build_tiny_eval_json(
                source_train_json=train_json.resolve(),
                output_json=output_root / "tiny_eval_ytvis.json",
            )
        if args.val_img_root is not None:
            val_img_root = args.val_img_root
        elif args.val_json is None:
            val_img_root = train_img_root
        else:
            val_img_root = _resolve_existing_path(
                [
                    repo_root / "data/LV-VIS/val/JPEGImages",
                    live_root / "data/LV-VIS/val/JPEGImages",
                ]
            )

    _write_smoke_config(
        config_path,
        weights_path=weights_path.resolve(),
        train_json=train_json.resolve(),
        train_img_root=train_img_root.resolve(),
        val_json=val_json.resolve(),
        val_img_root=val_img_root.resolve(),
    )

    train_script = repo_root / "train_seqformer_pseudo.py"
    if not train_script.exists():
        raise FileNotFoundError(f"missing train script: {train_script}")

    off_cmd = [
        args.python_bin,
        str(train_script),
        "-F",
        str(off_dir),
        "with",
        str(config_path),
    ]

    effective_on_weight = args.on_weight if args.on_weight is not None else (0.25 if args.on_mode in ("nonzero", "pilot") else 0.0)
    on_cmd = [
        args.python_bin,
        str(train_script),
        "-F",
        str(on_dir),
        "with",
        str(config_path),
        "stage_d_attribution.enabled=True",
        f"stage_d_attribution.stagec_artifact_root={args.stagec_artifact_root}",
        "stage_d_attribution.objective_coupling.enabled=True",
        "stage_d_attribution.objective_coupling.weight=0.0",
        "stage_d_attribution.additive_loss_key.enabled=True",
        f"stage_d_attribution.additive_loss_key.weight={effective_on_weight}",
        "stage_d_attribution.additive_loss_key.nonzero_semantics.enabled="
        f"{'True' if args.on_mode in ('nonzero', 'pilot') else 'False'}",
    ]
    if args.on_mode == "pilot":
        on_cmd.append(
            "stage_d_attribution.additive_loss_key.nonzero_semantics.mode=gradient_coupled_pilot_v1"
        )
        if args.pilot_scale is not None:
            on_cmd.append(
                "stage_d_attribution.additive_loss_key.nonzero_semantics.gradient_coupled_scale="
                f"{args.pilot_scale}"
            )

    if args.dry_run:
        on_nonzero_mode = "disabled"
        if args.on_mode == "nonzero":
            on_nonzero_mode = "constant"
        elif args.on_mode == "pilot":
            on_nonzero_mode = "gradient_coupled_pilot_v1"
        print("D10_DRY_RUN=1")
        print(f"D10_ON_MODE={args.on_mode}")
        print(f"D10_ON_NONZERO_MODE={on_nonzero_mode}")
        if args.pilot_scale is not None:
            print(f"D10_ON_PILOT_SCALE={args.pilot_scale}")
        print("D10_OFF_CMD=" + " ".join(off_cmd))
        print("D10_ON_CMD=" + " ".join(on_cmd))
        return 0

    _run(off_cmd, cwd=repo_root)
    _run(on_cmd, cwd=repo_root)

    off_metrics = _find_metrics_file(off_dir)
    on_metrics = _find_metrics_file(on_dir)
    off_rows = _load_metrics_rows(off_metrics)
    on_rows = _load_metrics_rows(on_metrics)
    on_runtime_cfg = _load_runtime_cfg(on_metrics.parent.parent)

    results = _evaluate_metrics_checks(
        off_rows=off_rows,
        on_rows=on_rows,
        total_loss_key=args.total_loss_key,
        parity_tol=args.parity_tol,
        expect_nonzero_on=args.on_mode in ("nonzero", "pilot"),
        nonzero_eps=args.nonzero_eps,
    )
    pilot_results = _evaluate_pilot_diagnostics_checks(
        on_mode=args.on_mode,
        on_runtime_cfg=on_runtime_cfg,
        expected_weight=float(effective_on_weight),
        pilot_scale=args.pilot_scale,
    )

    print(f"D10_OFF_METRICS={off_metrics}")
    print(f"D10_ON_METRICS={on_metrics}")
    print(f"D10_ON_RUNTIME_CFG={on_metrics.parent.parent / 'cfg_runtime.json'}")
    print(f"D10_ON_MODE={args.on_mode}")
    print(f"D10_OFF_HAS_LOSS_STAGE_D_ATTR={results['off_has_attr']}")
    print(f"D10_ON_HAS_LOSS_STAGE_D_ATTR={results['on_has_attr']}")
    print(f"D10_ON_LOSS_STAGE_D_ATTR={results['on_last_attr']}")
    print(f"D10_OFF_TOTAL_LOSS={results['off_total']:.15f}")
    print(f"D10_ON_TOTAL_LOSS={results['on_total']:.15f}")
    print(f"D10_TOTAL_LOSS_DIFF={results['total_diff']:.15f}")
    print(f"D10_TOTAL_LOSS_INCREASE={results['on_total_increase']:.15f}")
    print(f"D10_PARITY_TOL={args.parity_tol}")
    print(f"D10_NONZERO_EPS={args.nonzero_eps}")
    print(f"D10_ON_ZERO_OK={results['on_zero_ok']}")
    print(f"D10_ON_NONZERO_OK={results['on_nonzero_ok']}")
    print(f"D10_TOTAL_INCREASE_OK={results['total_increase_ok']}")
    print(f"D10_PILOT_DIAGNOSTICS_CHECK_ENABLED={pilot_results['enabled']}")
    print(f"D10_PILOT_DIAGNOSTICS_CHECKS_PASS={pilot_results['checks_ok']}")
    if pilot_results["enabled"]:
        print(f"D10_PILOT_NONZERO_MODE={pilot_results['nonzero_mode']}")
        print(f"D10_PILOT_NONZERO_ENABLED={pilot_results['nonzero_enabled']}")
        print(f"D10_PILOT_LOSS_WEIGHT={pilot_results['loss_weight']}")
        print(f"D10_PILOT_SCALE={pilot_results['gradient_coupled_scale']}")
        print(f"D10_PILOT_APPLIED={pilot_results['pilot_applied']}")
        print(f"D10_PILOT_STATE={pilot_results['pilot_state']}")
        print(f"D10_PILOT_SKIP_REASON={pilot_results['pilot_skip_reason']}")
        print(f"D10_PILOT_NONZERO_STATE={pilot_results['nonzero_state']}")
        print(f"D10_PILOT_NONZERO_SKIP_REASON={pilot_results['nonzero_skip_reason']}")
    print(f"D10_CHECKS_PASS={results['checks_ok']}")

    if results["checks_ok"]:
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
